"""
Supabase Migration Script (Phase 3)
=====================================
Architecture: Supabase = storage, FAISS stays in backend memory.

This script:
  1. Generates CREATE TABLE SQL with pgvector VECTOR(512)
  2. Creates IVFFlat index for vector similarity
  3. Exports local PostgreSQL data in batches of 1000
  4. Validates: row count, NULL embeddings, dimension check
  5. Generates .env template for Supabase config

Usage:
  python tools/supabase_migration.py --export    # Export to SQL file
  python tools/supabase_migration.py --validate  # Validate local DB
  python tools/supabase_migration.py --env       # Generate .env template
"""

import os
import sys
import json
import argparse

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "supabase_export")

DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "database": os.getenv("DB_NAME", "shopwhatyousee"),
    "user": os.getenv("DB_USER", "postgres"),
    "password": os.getenv("DB_PASS", "postgres123@"),
}

# ---- SQL Schema ----
SCHEMA_SQL = """-- Supabase Migration: visual_attributes
-- Architecture: Supabase = storage, FAISS = backend memory
-- DO NOT run similarity queries in Supabase. Use FAISS in backend.

-- Step 1: Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Step 2: Create table
CREATE TABLE IF NOT EXISTS visual_attributes (
    id SERIAL PRIMARY KEY,
    product_id TEXT NOT NULL UNIQUE,
    category TEXT,
    gender TEXT,
    style TEXT,
    material TEXT,
    price_bucket TEXT,
    color_family TEXT,
    brand TEXT,
    product_name TEXT,
    image_url TEXT,
    discounted_price NUMERIC,
    original_price NUMERIC,
    primary_color_name TEXT,
    pattern_value TEXT,
    sleeve_value TEXT,
    embedding VECTOR(512) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Step 3: Indexes for filtered queries
CREATE INDEX IF NOT EXISTS idx_va_category ON visual_attributes(category);
CREATE INDEX IF NOT EXISTS idx_va_gender ON visual_attributes(gender);
CREATE INDEX IF NOT EXISTS idx_va_product_id ON visual_attributes(product_id);

-- Step 4: IVFFlat vector index (for future pgvector similarity if needed)
-- lists=100 is appropriate for ~35K vectors (sqrt(35000) ~ 187, use 100 for speed)
-- NOTE: This index is for Supabase-side similarity. FAISS in backend is primary.
CREATE INDEX IF NOT EXISTS idx_va_embedding ON visual_attributes
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

-- Step 5: Row-level security (recommended for Supabase)
-- ALTER TABLE visual_attributes ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow read" ON visual_attributes FOR SELECT USING (true);
"""


def export_schema():
    """Export schema SQL to file."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = os.path.join(OUTPUT_DIR, "01_schema.sql")
    with open(path, "w") as f:
        f.write(SCHEMA_SQL)
    print(f"  Schema SQL -> {path}")
    return path


def export_data():
    """Export data from local PostgreSQL in batches of 1000."""
    import psycopg2

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    conn = psycopg2.connect(**DB_CONFIG)
    cur = conn.cursor()

    # Count total rows
    cur.execute("SELECT COUNT(*) FROM visual_attributes")
    total = cur.fetchone()[0]
    print(f"  Total rows: {total}")

    # Export in batches
    batch_size = 1000
    batch_num = 0
    exported = 0

    # Use server-side cursor for memory efficiency
    cur.execute("""
        SELECT
            product_id, category, gender, style, material,
            price_bucket, color_family, brand, product_name,
            image_url, discounted_price, original_price,
            primary_color_name, pattern_value, sleeve_value,
            embedding
        FROM visual_attributes
        ORDER BY id
    """)

    sql_file = os.path.join(OUTPUT_DIR, "02_data_insert.sql")
    with open(sql_file, "w") as f:
        f.write("-- Batch insert data (generated by supabase_migration.py)\n")
        f.write("-- Total rows: {}\n\n".format(total))

        batch = []
        for row in cur:
            (pid, cat, gen, sty, mat, pbk, cfm, brand, pname,
             img_url, dprice, oprice, pcolor, pattern, sleeve, emb) = row

            # Format embedding as pgvector literal
            if isinstance(emb, list):
                emb_str = "[" + ",".join(str(v) for v in emb) + "]"
            elif isinstance(emb, str):
                emb_str = emb
            else:
                emb_str = str(emb)

            def sql_val(v):
                if v is None:
                    return "NULL"
                if isinstance(v, (int, float)):
                    return str(v)
                s = str(v).replace("'", "''")
                return f"'{s}'"

            values = (
                f"({sql_val(pid)}, {sql_val(cat)}, {sql_val(gen)}, "
                f"{sql_val(sty)}, {sql_val(mat)}, {sql_val(pbk)}, "
                f"{sql_val(cfm)}, {sql_val(brand)}, {sql_val(pname)}, "
                f"{sql_val(img_url)}, {sql_val(dprice)}, {sql_val(oprice)}, "
                f"{sql_val(pcolor)}, {sql_val(pattern)}, {sql_val(sleeve)}, "
                f"'{emb_str}')"
            )
            batch.append(values)
            exported += 1

            if len(batch) >= batch_size:
                batch_num += 1
                f.write(f"-- Batch {batch_num} ({len(batch)} rows)\n")
                f.write(
                    "INSERT INTO visual_attributes "
                    "(product_id, category, gender, style, material, "
                    "price_bucket, color_family, brand, product_name, "
                    "image_url, discounted_price, original_price, "
                    "primary_color_name, pattern_value, sleeve_value, embedding) "
                    "VALUES\n"
                )
                f.write(",\n".join(batch))
                f.write("\nON CONFLICT (product_id) DO NOTHING;\n\n")
                batch = []
                print(f"    Batch {batch_num}: {exported}/{total}")

        # Final batch
        if batch:
            batch_num += 1
            f.write(f"-- Batch {batch_num} ({len(batch)} rows)\n")
            f.write(
                "INSERT INTO visual_attributes "
                "(product_id, category, gender, style, material, "
                "price_bucket, color_family, brand, product_name, "
                "image_url, discounted_price, original_price, "
                "primary_color_name, pattern_value, sleeve_value, embedding) "
                "VALUES\n"
            )
            f.write(",\n".join(batch))
            f.write("\nON CONFLICT (product_id) DO NOTHING;\n\n")
            print(f"    Batch {batch_num}: {exported}/{total}")

    cur.close()
    conn.close()

    print(f"  Data SQL -> {sql_file} ({exported} rows in {batch_num} batches)")
    return sql_file


def export_validation():
    """Generate validation SQL."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = os.path.join(OUTPUT_DIR, "03_validate.sql")
    with open(path, "w") as f:
        f.write("""-- Validation queries (run after import)

-- 1. Row count
SELECT COUNT(*) AS total_rows FROM visual_attributes;

-- 2. NULL embeddings (should be 0)
SELECT COUNT(*) AS null_embeddings
FROM visual_attributes
WHERE embedding IS NULL;

-- 3. Dimension check (should all be 512)
SELECT vector_dims(embedding) AS dim, COUNT(*) AS cnt
FROM visual_attributes
GROUP BY vector_dims(embedding);

-- 4. Category distribution
SELECT category, COUNT(*) AS cnt
FROM visual_attributes
GROUP BY category
ORDER BY cnt DESC;

-- 5. Sample similarity query (for testing pgvector)
-- SELECT product_id, category,
--        1 - (embedding <=> (SELECT embedding FROM visual_attributes LIMIT 1)) AS similarity
-- FROM visual_attributes
-- ORDER BY embedding <=> (SELECT embedding FROM visual_attributes LIMIT 1)
-- LIMIT 5;
""")
    print(f"  Validation SQL -> {path}")
    return path


def validate_local():
    """Validate local PostgreSQL data before export."""
    import psycopg2

    print("\n  Validating local DB...")
    conn = psycopg2.connect(**DB_CONFIG)
    cur = conn.cursor()

    # Row count
    cur.execute("SELECT COUNT(*) FROM visual_attributes")
    total = cur.fetchone()[0]
    print(f"    Total rows: {total}")

    # NULL embeddings
    cur.execute("SELECT COUNT(*) FROM visual_attributes WHERE embedding IS NULL")
    nulls = cur.fetchone()[0]
    print(f"    NULL embeddings: {nulls} {'PASS' if nulls == 0 else 'FAIL'}")

    # Dimension check (sample)
    cur.execute("SELECT array_length(embedding, 1) FROM visual_attributes LIMIT 1")
    dim = cur.fetchone()[0]
    print(f"    Embedding dimension: {dim} {'PASS' if dim == 512 else 'FAIL'}")

    # Category distribution
    cur.execute("SELECT category, COUNT(*) FROM visual_attributes GROUP BY category ORDER BY COUNT(*) DESC")
    cats = cur.fetchall()
    print(f"    Categories: {len(cats)}")
    for cat, cnt in cats:
        print(f"      {cat}: {cnt}")

    cur.close()
    conn.close()

    return nulls == 0 and dim == 512


def generate_env_template():
    """Generate .env template for Supabase config."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = os.path.join(OUTPUT_DIR, "supabase.env.template")
    with open(path, "w") as f:
        f.write("""# Supabase Configuration Template
# Copy to .env and fill in your Supabase project details

# Supabase Database (direct connection)
SUPABASE_DB_HOST=db.YOUR_PROJECT_REF.supabase.co
SUPABASE_DB_PORT=5432
SUPABASE_DB_NAME=postgres
SUPABASE_DB_USER=postgres
SUPABASE_DB_PASS=YOUR_DATABASE_PASSWORD

# Supabase API (for REST API access)
SUPABASE_URL=https://YOUR_PROJECT_REF.supabase.co
SUPABASE_ANON_KEY=YOUR_ANON_KEY
SUPABASE_SERVICE_KEY=YOUR_SERVICE_ROLE_KEY

# Connection Pooling (recommended for production)
# Use pgBouncer endpoint for connection pooling
SUPABASE_POOLER_HOST=db.YOUR_PROJECT_REF.supabase.co
SUPABASE_POOLER_PORT=6543

# Architecture Note:
# - Supabase = storage (metadata + embeddings backup)
# - FAISS = backend memory (primary similarity search)
# - Do NOT run similarity queries through Supabase for latency-sensitive paths
""")
    print(f"  Env template -> {path}")
    return path


def main():
    parser = argparse.ArgumentParser(description="Supabase Migration Tool")
    parser.add_argument("--export", action="store_true", help="Export schema + data + validation SQL")
    parser.add_argument("--validate", action="store_true", help="Validate local DB")
    parser.add_argument("--env", action="store_true", help="Generate .env template")
    parser.add_argument("--all", action="store_true", help="Do everything")
    args = parser.parse_args()

    if not any([args.export, args.validate, args.env, args.all]):
        args.all = True  # Default: do everything

    print("=" * 60)
    print("SUPABASE MIGRATION TOOL")
    print("=" * 60)

    if args.validate or args.all:
        print("\n[1] Validating local DB...")
        validate_local()

    if args.export or args.all:
        print("\n[2] Exporting schema...")
        export_schema()
        print("\n[3] Exporting data...")
        export_data()
        print("\n[4] Generating validation SQL...")
        export_validation()

    if args.env or args.all:
        print("\n[5] Generating .env template...")
        generate_env_template()

    print(f"\n{'=' * 60}")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
